#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import OrderedDict
from pathlib import Path

APP_MODULE: str = "Production Entry App"
CORE_DOCTYPES: tuple[str, ...] = (
	"Stock Entry",
	"Stock Entry Detail",
	"Item",
	"Workstation",
	"Manufacturing Settings",
	"Downtime Entry",
)

ROOT = Path(__file__).resolve().parents[1]
FIXTURE_PATH = ROOT / "production_entry_app" / "fixtures" / "custom_field.json"
OUTPUT_PATH = ROOT / "production_entry_app" / "public" / "js" / "generated_access_control_field_map.js"


def build_access_control_field_map() -> OrderedDict[str, list[str]]:
	"""Derive the denied-user field-hide map from the app custom-field fixture."""
	field_map: OrderedDict[str, list[str]] = OrderedDict((doctype, []) for doctype in CORE_DOCTYPES)
	custom_fields = json.loads(FIXTURE_PATH.read_text())
	for row in custom_fields:
		if row.get("module") != APP_MODULE:
			continue
		doctype = row.get("dt")
		fieldname = row.get("fieldname")
		if doctype not in field_map or not fieldname:
			continue
		field_map[doctype].append(str(fieldname))
	return field_map


def render_js(field_map: OrderedDict[str, list[str]]) -> str:
	"""Render a browser-friendly JS artifact with a CommonJS fallback."""
	payload = json.dumps(field_map, indent=2, ensure_ascii=True)
	return (
		"// This file is generated by scripts/build_access_control_field_map.py.\n"
		"// Do not edit by hand.\n\n"
		"(function () {\n"
		f"\tconst GENERATED_ACCESS_CONTROL_FIELD_MAP = {payload};\n"
		"\tconst api = GENERATED_ACCESS_CONTROL_FIELD_MAP;\n"
		"\tif (typeof window !== \"undefined\") {\n"
		"\t\tconst PEA = (window.production_entry_app = window.production_entry_app || {});\n"
		"\t\tPEA.generated_access_control_field_map = api;\n"
		"\t}\n"
		"\tif (typeof module !== \"undefined\" && module.exports) {\n"
		"\t\tmodule.exports = api;\n"
		"\t}\n"
		"})();\n"
	)


def write_output(field_map: OrderedDict[str, list[str]]) -> None:
	OUTPUT_PATH.write_text(render_js(field_map))


def main() -> int:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--check", action="store_true", help="Fail if the generated file is out of date.")
	args = parser.parse_args()

	field_map = build_access_control_field_map()
	rendered = render_js(field_map)

	if args.check:
		current = OUTPUT_PATH.read_text() if OUTPUT_PATH.exists() else ""
		if current != rendered:
			raise SystemExit("generated_access_control_field_map.js is out of date")
		return 0

	write_output(field_map)
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
